[build]
  command = "npm run build"
  publish = "."
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://generativelanguage.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://generativelanguage.googleapis.com https://nsymqiqcfbxtdaxhvaut.supabase.co; img-src 'self' data:;"

[[redirects]]
  from = "/api/health-advice"
  to = "/.netlify/functions/gemini-chat-standalone"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200